#!/usr/bin/env bash
nix_folder="$HOME/nix"

linenumber=$(sed -n '/st.overrideAttrs/=' "${nix_folder}/config/base.nix")
((linenumber+=3))


git add .
timestamp=$(printf "%(%H:%M:%S)T\\n" "-1") 
git commit -m "build: ${timestamp}"
git push
working_dir="$(pwd)"
git_revision="$(git log | head -1 | awk '{print $2;}')"
replace_pattern="      rev = \"${git_revision}\";"
sed -i "${linenumber}s/.*/${replace_pattern}/" "${nix_folder}/config/base.nix"
sudo nixos-rebuild switch --flake "${nix_folder}#laptop"
cd "${working_dir}" || exit 0

